server:
  port: 8180
spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB
  devtools:
    restart:
      enabled: false
  application:
    name: hybrid-business
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3316/hybrid?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5 #最小连接数
      maximum-pool-size: 20 #池中最大连接数
      connection-timeout: 20000 #连接超时时间 ms
      idle-timeout: 30000 #空闲等待时间 ms
      max-lifetime: 1800000 #连接在连接池存活时间 ms
  elasticsearch:
    uris:
      - http://192.168.40.100:9200
  rabbitmq:
    addresses: 192.168.40.100:5672
    username: admin
    password: admin
    publisher-returns: true

plugin:
  prevent-repeat:
    token-key:
  redis:
    data-sources:
      redis01:
        host: localhost
        port: 6379
        database: 10
        lettuce:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
