server:
  port: 8180
spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB
  devtools:
    restart:
      enabled: false
  application:
    name: hybrid-business
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3316/hybrid?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5 #最小连接数
      maximum-pool-size: 20 #池中最大连接数
      connection-timeout: 20000 #连接超时时间 ms
      idle-timeout: 30000 #空闲等待时间 ms
      max-lifetime: 1800000 #连接在连接池存活时间 ms
plugin:
  prevent-repeat:
    token-key:
  redis:
    data-sources:
      redis01:
        host: localhost
        port: 6379
        database: 1
        lettuce:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
      redis02:
        host: localhost
        port: 6379
        database: 2
        lettuce:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
#      redis03:
#        cluster:
#          nodes: 192.168.40.100:7001,192.168.40.100:7002,192.168.40.100:7003,192.168.40.100:7004,192.168.40.100:7005,192.168.40.100:7006
#        password: 123456
#        lettuce:
#          pool:
#            max-active: 8
#            max-idle: 8
#            min-idle: 0
